name: ${PROJECT_TAG:-monitoring}

services:
  prometheus:
    image: prom/prometheus:${PROMETHEUS_VERSION:-latest}
    restart: unless-stopped
    user: "nobody"
    env_file:
      - .env
    command:
      [
        "--config.file=/etc/prometheus/prometheus.yml",
        "--log.level=warn",
        "--storage.tsdb.path=/prometheus",
        "--storage.tsdb.retention.time=90d",
        "--storage.tsdb.retention.size=20GB",
      ]
    volumes:
      - prometheus_data:/prometheus:rw
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/rules:/etc/prometheus/rules:ro
      - ./prometheus/targets:/etc/prometheus/targets:ro
    ports:
      - "9090:9090"
    healthcheck:
      test:
        ["CMD", "wget", "-O", "/dev/null", "http://localhost:9090/-/healthy"]
      interval: 120s
      timeout: 5s
      retries: 2

  grafana:
    image: grafana/grafana:${GRAFANA_VERSION:-latest}
    restart: unless-stopped
    user: "472"
    depends_on:
      - prometheus
    env_file:
      - .env
    volumes:
      - grafana_data:/var/lib/grafana:rw
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    ports:
      - "3000:3000"
    healthcheck:
      test:
        ["CMD", "wget", "-O", "/dev/null", "http://localhost:3000/api/health"]
      interval: 120s
      timeout: 5s
      retries: 2

  # https://grafana.com/docs/grafana/latest/setup-grafana/image-rendering/
  grafana-image-renderer:
    image: grafana/grafana-image-renderer:${GRAFANA_IMAGE_RENDERER_VERSION:-latest}
    restart: unless-stopped
    env_file:
      - .env

  loki:
    image: grafana/loki:${LOKI_VERSION:-latest}
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - loki_data:/loki:rw
      # - ./loki:/etc/loki:ro
    ports:
      - "3100:3100"
    healthcheck:
      test: ["CMD", "wget", "-O", "/dev/null", "http://localhost:3100/ready"]
      interval: 120s
      timeout: 5s
      retries: 2

  cadvisor:
    container_name: ${PROJECT_TAG:-monitoring}-cadvisor
    image: gcr.io/cadvisor/cadvisor:${CADVISOR_VERSION:-latest}
    restart: unless-stopped
    env_file:
      - .env
    cap_add:
      - SYS_ADMIN
    # https://github.com/google/cadvisor/blob/master/docs/runtime_options.md
    command:
      [
        "-housekeeping_interval=30s",
        "-docker_only=true",
        "-store_container_labels=false",
      ]
    devices:
      - /dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
      - /etc/machine-id:/etc/machine-id:ro
    healthcheck:
      test: ["CMD", "wget", "-O", "/dev/null", "http://localhost:8080/healthz"]
      interval: 120s
      timeout: 5s
      retries: 2

  blackbox-exporter:
    image: prom/blackbox-exporter:${BLACKBOX_EXPORTER_VERSION:-latest}
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./blackbox-exporter/config.yml:/etc/blackbox_exporter/config.yml:ro
    ports:
      - "9115:9115"
    command: ["--config.file=/etc/blackbox_exporter/config.yml"]
    healthcheck:
      test: ["CMD", "wget", "-O", "/dev/null", "http://localhost:9115/health"]
      interval: 120s
      timeout: 5s
      retries: 2

volumes:
  grafana_data:
  prometheus_data:
  loki_data:
