# https://grafana.com/docs/grafana/latest/administration/provisioning/#alerting
# https://grafana.com/docs/grafana/latest/alerting/set-up/provision-alerting-resources/file-provisioning
apiVersion: 1

groups:
  - orgId: 1
    name: prometheus_rules
    folder: prometheus
    interval: 60s
    rules:
      - uid: prometheus_exporter_down
        title: Prometheus Exporter Down
        condition: A
        data:
          - refId: A
            datasourceUid: DS_PROMETHEUS
            relativeTimeRange:
              from: 600
              to: 0
            model:
              expr: 'up{job=~''node_exporter''} == 0'
              instant: true
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A
        dashboardUid: CHANGE_ME
        noDataState: OK
        execErrState: Alerting
        for: 1m
        annotations:
          summary: "Prometheus exporter seems down"
          description: "The node exporter is not responding\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
        labels:
          severity: error
          env: prod
          receiver: telegram
        isPaused: false
      - uid: prometheus_configuration_reload_failure
        title: Prometheus Configuration Reload Failure
        condition: A
        data:
          - refId: A
            datasourceUid: DS_PROMETHEUS
            relativeTimeRange:
              from: 600
              to: 0
            model:
              expr: 'prometheus_config_last_reload_successful != 1'
              instant: true
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A
        dashboardUid: CHANGE_ME
        noDataState: OK
        execErrState: Alerting
        for: 0m
        annotations:
          summary: "Prometheus configuration reload failure (instance {{ $labels.instance }})"
          description: "Prometheus configuration reload error\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
        labels:
          severity: error
          env: prod
          receiver: telegram
        isPaused: false
      - uid: prometheus_too_many_restarts
        title: Prometheus Too Many Restarts
        condition: A
        data:
          - refId: A
            datasourceUid: DS_PROMETHEUS
            relativeTimeRange:
              from: 600
              to: 0
            model:
              expr: 'changes(process_start_time_seconds{job=~"prometheus|pushgateway|alertmanager"}[15m]) > 4'
              instant: true
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A
        dashboardUid: CHANGE_ME
        noDataState: OK
        execErrState: Alerting
        for: 0m
        annotations:
          summary: "Prometheus too many restarts (instance {{ $labels.instance }})"
          description: "Prometheus has restarted more than twice in the last 15 minutes. It might be crashlooping.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
        labels:
          severity: warn
          env: prod
          receiver: telegram
        isPaused: false
      - uid: prometheus_targets_empty
        title: Prometheus Targets Empty
        condition: A
        data:
          - refId: A
            datasourceUid: DS_PROMETHEUS
            relativeTimeRange:
              from: 600
              to: 0
            model:
              expr: 'prometheus_sd_discovered_targets == 0'
              instant: true
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A
        dashboardUid: CHANGE_ME
        noDataState: OK
        execErrState: Alerting
        for: 5m
        annotations:
          summary: "Prometheus targets empty"
          description: "Prometheus targets empty\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
        labels:
          severity: error
          env: prod
          receiver: telegram
        isPaused: false
      - uid: prometheus_job_missing
        title: Prometheus Job Missing
        condition: A
        data:
          - refId: A
            datasourceUid: DS_PROMETHEUS
            relativeTimeRange:
              from: 600
              to: 0
            model:
              expr: 'absent(up{job=''prometheus''})'
              instant: true
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A
        dashboardUid: CHANGE_ME
        noDataState: OK
        execErrState: Alerting
        for: 5m
        annotations:
          summary: "Prometheus job missing (instance {{ $labels.instance }})"
          description: "A Prometheus job has disappeared\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
        labels:
          severity: error
          env: prod
          receiver: telegram
        isPaused: false
      - uid: prometheus_alertmanager_job_missing
        title: Prometheus AlertManager Job Missing
        condition: A
        data:
          - refId: A
            datasourceUid: DS_PROMETHEUS
            relativeTimeRange:
              from: 600
              to: 0
            model:
              expr: 'absent(up{job=''alertmanager''})'
              instant: true
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A
        dashboardUid: CHANGE_ME
        noDataState: OK
        execErrState: Alerting
        for: 5m
        annotations:
          summary: "Prometheus AlertManager job missing (instance {{ $labels.instance }})"
          description: "A Prometheus AlertManager job has disappeared\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
        labels:
          severity: error
          env: prod
          receiver: telegram
        isPaused: false
      - uid: prometheus_not_connected_to_alertmanager
        title: Prometheus Not Connected To Alertmanager
        condition: A
        data:
          - refId: A
            datasourceUid: DS_PROMETHEUS
            relativeTimeRange:
              from: 600
              to: 0
            model:
              expr: 'prometheus_notifications_alertmanagers_discovered < 1'
              instant: true
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A
        dashboardUid: CHANGE_ME
        noDataState: OK
        execErrState: Alerting
        for: 5m
        annotations:
          summary: "Prometheus not connected to alertmanager (instance {{ $labels.instance }})"
          description: "Prometheus cannot connect the alertmanager\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
        labels:
          severity: error
          env: prod
          receiver: telegram
        isPaused: false
      - uid: prometheus_template_text_expansion_failures
        title: Prometheus Template Text Expansion Failures
        condition: A
        data:
          - refId: A
            datasourceUid: DS_PROMETHEUS
            relativeTimeRange:
              from: 600
              to: 0
            model:
              expr: 'increase(prometheus_template_text_expansion_failures_total[3m]) > 0'
              instant: true
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A
        dashboardUid: CHANGE_ME
        noDataState: OK
        execErrState: Alerting
        for: 0m
        annotations:
          summary: "Prometheus template text expansion failures (instance {{ $labels.instance }})"
          description: "Prometheus encountered {{ $value }} template text expansion failures\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
        labels:
          severity: error
          env: prod
          receiver: telegram
        isPaused: false
      - uid: prometheus_notifications_backlog
        title: Prometheus Notifications Backlog
        condition: A
        data:
          - refId: A
            datasourceUid: DS_PROMETHEUS
            relativeTimeRange:
              from: 600
              to: 0
            model:
              expr: 'min_over_time(prometheus_notifications_queue_length[10m]) > 0'
              instant: true
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A
        dashboardUid: CHANGE_ME
        noDataState: OK
        execErrState: Alerting
        for: 0m
        annotations:
          summary: "Prometheus notifications backlog (instance {{ $labels.instance }})"
          description: "The Prometheus notification queue has not been empty for 10 minutes\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
        labels:
          severity: error
          env: prod
          receiver: telegram
        isPaused: false
      - uid: prometheus_alertmanager_notification_failing
        title: Prometheus AlertManager Notification Failing
        condition: A
        data:
          - refId: A
            datasourceUid: DS_PROMETHEUS
            relativeTimeRange:
              from: 600
              to: 0
            model:
              expr: 'rate(alertmanager_notifications_failed_total[1m]) > 0'
              instant: true
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A
        dashboardUid: CHANGE_ME
        noDataState: OK
        execErrState: Alerting
        for: 0m
        annotations:
          summary: "Prometheus AlertManager notification failing (instance {{ $labels.instance }})"
          description: "Alertmanager is failing sending notifications\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
        labels:
          severity: error
          env: prod
          receiver: telegram
        isPaused: false
      - uid: prometheus_tsdb_checkpoint_creation_failures
        title: Prometheus TSDB Checkpoint Creation Failures
        condition: A
        data:
          - refId: A
            datasourceUid: DS_PROMETHEUS
            relativeTimeRange:
              from: 600
              to: 0
            model:
              expr: 'increase(prometheus_tsdb_checkpoint_creations_failed_total[1m]) > 0'
              instant: true
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A
        dashboardUid: CHANGE_ME
        noDataState: OK
        execErrState: Alerting
        for: 0m
        annotations:
          summary: "Prometheus TSDB checkpoint creation failures (instance {{ $labels.instance }})"
          description: "Prometheus encountered {{ $value }} checkpoint creation failures\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
        labels:
          severity: error
          env: prod
          receiver: telegram
        isPaused: false
      - uid: prometheus_tsdb_checkpoint_deletion_failures
        title: Prometheus TSDB Checkpoint Deletion Failures
        condition: A
        data:
          - refId: A
            datasourceUid: DS_PROMETHEUS
            relativeTimeRange:
              from: 600
              to: 0
            model:
              expr: 'increase(prometheus_tsdb_checkpoint_deletions_failed_total[1m]) > 0'
              instant: true
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A
        dashboardUid: CHANGE_ME
        noDataState: OK
        execErrState: Alerting
        for: 0m
        annotations:
          summary: "Prometheus TSDB checkpoint deletion failures (instance {{ $labels.instance }})"
          description: "Prometheus encountered {{ $value }} checkpoint deletion failures\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
        labels:
          severity: error
          env: prod
          receiver: telegram
        isPaused: false
      - uid: prometheus_tsdb_compactions_failed
        title: Prometheus TSDB Compactions Failed
        condition: A
        data:
          - refId: A
            datasourceUid: DS_PROMETHEUS
            relativeTimeRange:
              from: 600
              to: 0
            model:
              expr: 'increase(prometheus_tsdb_compactions_failed_total[1m]) > 0'
              instant: true
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A
        dashboardUid: CHANGE_ME
        noDataState: OK
        execErrState: Alerting
        for: 0m
        annotations:
          summary: "Prometheus TSDB compactions failed (instance {{ $labels.instance }})"
          description: "Prometheus encountered {{ $value }} TSDB compactions failures\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
        labels:
          severity: error
          env: prod
          receiver: telegram
        isPaused: false
      - uid: prometheus_tsdb_head_truncations_failed
        title: Prometheus TSDB Head Truncations Failed
        condition: A
        data:
          - refId: A
            datasourceUid: DS_PROMETHEUS
            relativeTimeRange:
              from: 600
              to: 0
            model:
              expr: 'increase(prometheus_tsdb_head_truncations_failed_total[1m]) > 0'
              instant: true
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A
        dashboardUid: CHANGE_ME
        noDataState: OK
        execErrState: Alerting
        for: 0m
        annotations:
          summary: "Prometheus TSDB head truncations failed (instance {{ $labels.instance }})"
          description: "Prometheus encountered {{ $value }} TSDB head truncation failures\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
        labels:
          severity: error
          env: prod
          receiver: telegram
        isPaused: false
      - uid: prometheus_tsdb_reload_failures
        title: Prometheus TSDB Reload Failures
        condition: A
        data:
          - refId: A
            datasourceUid: DS_PROMETHEUS
            relativeTimeRange:
              from: 600
              to: 0
            model:
              expr: 'increase(prometheus_tsdb_reloads_failures_total[1m]) > 0'
              instant: true
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A
        dashboardUid: CHANGE_ME
        noDataState: OK
        execErrState: Alerting
        for: 0m
        annotations:
          summary: "Prometheus TSDB reload failures (instance {{ $labels.instance }})"
          description: "Prometheus encountered {{ $value }} TSDB reload failures\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
        labels:
          severity: error
          env: prod
          receiver: telegram
        isPaused: false
      - uid: prometheus_tsdb_wal_corruptions
        title: Prometheus TSDB WAL Corruptions
        condition: A
        data:
          - refId: A
            datasourceUid: DS_PROMETHEUS
            relativeTimeRange:
              from: 600
              to: 0
            model:
              expr: 'increase(prometheus_tsdb_wal_corruptions_total[1m]) > 0'
              instant: true
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A
        dashboardUid: CHANGE_ME
        noDataState: OK
        execErrState: Alerting
        for: 0m
        annotations:
          summary: "Prometheus TSDB WAL corruptions (instance {{ $labels.instance }})"
          description: "Prometheus encountered {{ $value }} TSDB WAL corruptions\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
        labels:
          severity: error
          env: prod
          receiver: telegram
        isPaused: false
      - uid: prometheus_tsdb_wal_truncations_failed
        title: Prometheus TSDB WAL Truncations Failed
        condition: A
        data:
          - refId: A
            datasourceUid: DS_PROMETHEUS
            relativeTimeRange:
              from: 600
              to: 0
            model:
              expr: 'increase(prometheus_tsdb_wal_truncations_failed_total[1m]) > 0'
              instant: true
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A
        dashboardUid: CHANGE_ME
        noDataState: OK
        execErrState: Alerting
        for: 0m
        annotations:
          summary: "Prometheus TSDB WAL truncations failed (instance {{ $labels.instance }})"
          description: "Prometheus encountered {{ $value }} TSDB WAL truncation failures\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
        labels:
          severity: error
          env: prod
          receiver: telegram
        isPaused: false
