# https://prometheus.io/docs/prometheus/latest/configuration/configuration
global:
  scrape_interval: 30s
  evaluation_interval: 1m
  scrape_timeout: 10s

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: ["alertmanager:9093"]

rule_files:
  - /etc/prometheus/rules/*.yml
  - /etc/prometheus/rules/*.yaml
  - /etc/prometheus/rules/*.rules

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "alertmanager"
    static_configs:
      - targets: ["alertmanager:9093"]

  - job_name: "grafana"
    static_configs:
      - targets: ["grafana:3000"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "node_exporter"
    file_sd_configs:
      - files:
          - "targets/node_exporter.yml"

  - job_name: "blackbox_exporter"
    static_configs:
      - targets: ["blackbox-exporter:9115"]

  - job_name: "fail2ban_exporter"
    file_sd_configs:
      - files:
          - "targets/fail2ban_exporter.yml"

  # - job_name: "nginx_exporter"
  #   file_sd_configs:
  #     - files:
  #         - "targets/nginx_exporter.yml"

  - job_name: "blackbox_http"
    metrics_path: /probe
    params:
      module: [http]
    file_sd_configs:
      - files:
          - "targets/blackbox_http.yml"
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: "blackbox_icmp"
    metrics_path: /probe
    params:
      module: [icmp]
    file_sd_configs:
      - files:
          - "targets/blackbox_icmp.yml"
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: "blackbox_icmp_home"
    metrics_path: /probe
    params:
      module: [icmp]
    file_sd_configs:
      - files:
          - "targets/blackbox_icmp_home.yml"
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
