# https://samber.github.io/awesome-prometheus-alerts/rules#blackbox
groups:
  - name: blackbox_icmp
    rules:
      - alert: IcmpEndpointDown
        expr: "probe_success{job='blackbox_icmp'} == 0"
        for: 5m
        labels:
          severity: error
        annotations:
          summary: "ICMP request failure"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5m"

      - alert: SlowPing
        expr: "avg_over_time(probe_icmp_duration_seconds[1m]) > 1"
        for: 5m
        labels:
          severity: error
        annotations:
          summary: "Blackbox probe slow ping"
          description: "Ping took more than 1s\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
