# https://samber.github.io/awesome-prometheus-alerts/rules#blackbox
groups:
  - name: blackbox_http
    rules:
      - alert: HttpEndpointDown
        expr: "probe_http_status_code <= 199 OR probe_http_status_code >= 400"
        for: 5m
        labels:
          severity: error
        annotations:
          summary: "Blackbox probe HTTP failure"
          description: "HTTP status code is not 200-399\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: SslCertificateWillExpireSoon
        expr: "0 <= round((last_over_time(probe_ssl_earliest_cert_expiry[10m]) - time()) / 86400, 0.1) < 5"
        for: 0m
        labels:
          severity: error
        annotations:
          summary: "Blackbox SSL certificate will expire soon"
          description: "SSL certificate expires in less than 5 days\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: SslCertificateExpired
        expr: "round((last_over_time(probe_ssl_earliest_cert_expiry[10m]) - time()) / 86400, 0.1) < 0"
        for: 0m
        labels:
          severity: error
        annotations:
          summary: "Blackbox SSL certificate expired"
          description: "SSL certificate has expired already\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: SslCertificateChanged
        expr: "changes(probe_ssl_last_chain_info[5m]) != 0"
        for: 5m
        labels:
          severity: error
        annotations:
          summary: "SSL certificate metadata value changed"
          description: "The metric value 'probe_ssl_last_chain_info' has changed in the 5m\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: SlowHttp
        expr: "avg_over_time(probe_http_duration_seconds[1m]) > 1"
        for: 5m
        labels:
          severity: error
        annotations:
          summary: "Blackbox probe slow HTTP"
          description: "HTTP request took more than 1s\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
