# https://samber.github.io/awesome-prometheus-alerts/rules#host-and-hardware
groups:
  - name: node_exporter
    rules:
      - alert: RebootRequired
        expr: "node_reboot_required > 0"
        labels:
          severity: warn
        annotations:
          description: "{{ $labels.instance }} requires a reboot."
          summary: "Reboot required"

      - alert: InstanceHighCpuUsage
        expr: '100 - (avg by (instance, env, service) (rate(node_cpu_seconds_total{mode="idle"}[10m])) * 100) > 90'
        labels:
          severity: error
        annotations:
          summary: "CPU usage is at 90%"

      - alert: InstanceRamSpaceFillingUp
        expr: "node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100 < 15"
        for: 5m
        labels:
          severity: warn
        annotations:
          summary: "RAM memory has less than 15% space left"

      - alert: InstanceRamOutOfSpace
        expr: "node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100 < 5"
        for: 5m
        labels:
          severity: error
        annotations:
          summary: "RAM memory has less than 5% space left"

      - alert: InstanceFilesystemSpaceFillingUp
        annotations:
          description: 'Filesystem on {{ $labels.device }} at {{ $labels.instance }} has only {{ printf "%.2f" $value }}% available space left and is filling up.'
          summary: "Filesystem is predicted to run out of space within the next 24 hours"
        expr: "(\n  node_filesystem_avail_bytes{fstype!=\"\"} / node_filesystem_size_bytes{fstype!=\"\"} * 100 < 40\nand\n  predict_linear(node_filesystem_avail_bytes{fstype!=\"\"}[6h], 24*60*60) < 0\nand\n  node_filesystem_readonly{fstype!=\"\"} == 0\n)\n"
        for: 1h
        labels:
          severity: warn

      - alert: InstanceFilesystemSpaceFillingUp
        annotations:
          description: 'Filesystem on {{ $labels.device }} at {{ $labels.instance }} has only {{ printf "%.2f" $value }}% available space left and is filling up fast.'
          summary: "Filesystem is predicted to run out of space within the next 12 hours"
        expr: "(\n  node_filesystem_avail_bytes{fstype!=\"\"} / node_filesystem_size_bytes{fstype!=\"\"} * 100 < 20\nand\n  predict_linear(node_filesystem_avail_bytes{fstype!=\"\"}[6h], 12*60*60) < 0\nand\n  node_filesystem_readonly{fstype!=\"\"} == 0\n)\n"
        for: 1h
        labels:
          severity: error

      - alert: InstanceFilesystemAlmostOutOfSpace
        annotations:
          description: 'Filesystem on {{ $labels.device }} at {{ $labels.instance }} has only {{ printf "%.2f" $value }}% available space left.'
          summary: "Filesystem has less than 15% space left"
        expr: "(\n  node_filesystem_avail_bytes{fstype!=\"\"} / node_filesystem_size_bytes{fstype!=\"\"} * 100 < 15\nand\n  node_filesystem_readonly{fstype!=\"\"} == 0\n)\n"
        for: 5m
        labels:
          severity: warn

      - alert: InstanceFilesystemOutOfSpace
        annotations:
          description: 'Filesystem on {{ $labels.device }} at {{ $labels.instance }} has only {{ printf "%.2f" $value }}% available space left.'
          summary: "Filesystem has less than 5% space left"
        expr: "(\n  node_filesystem_avail_bytes{fstype!=\"\"} / node_filesystem_size_bytes{fstype!=\"\"} * 100 < 5\nand\n  node_filesystem_readonly{fstype!=\"\"} == 0\n)\n"
        for: 5m
        labels:
          severity: error

      - alert: InstanceSwapSpaceFillingUp
        expr: (1 - (node_memory_SwapFree_bytes / node_memory_SwapTotal_bytes)) * 100 > 70
        for: 2m
        labels:
          severity: warn
        annotations:
          summary: "Swap memory has less than 30% space left"

      - alert: InstanceSwapOutOfSpace
        expr: "(1 - (node_memory_SwapFree_bytes / node_memory_SwapTotal_bytes)) * 100 > 90"
        for: 2m
        labels:
          severity: error
        annotations:
          summary: "Swap memory has less than 10% space left"

      - alert: InstanceNetworkReceiveErrors
        annotations:
          description: '{{ $labels.instance }} interface {{ $labels.device }} has encountered {{ printf "%.0f" $value }} receive errors in the last two minutes.'
          summary: "Network interface '{{ $labels.device }}' is reporting many receive errors"
        expr: "increase(node_network_receive_errs_total[2m]) > 10\n"
        for: 1h
        labels:
          severity: error

      - alert: InstanceNetworkTransmitErrors
        annotations:
          description: '{{ $labels.instance }} interface {{ $labels.device }} has encountered {{ printf "%.0f" $value }} transmit errors in the last two minutes.'
          summary: "Network interface '{{ $labels.device }}' is reporting many transmit errors"
        expr: "increase(node_network_transmit_errs_total[2m]) > 10\n"
        for: 1h
        labels:
          severity: error

      - alert: InstanceHighNumberConntrackEntriesUsed
        annotations:
          description: "{{ $value | humanizePercentage }} of conntrack entries are used"
          summary: "Number of conntrack are getting close to the limit"
        expr: "(node_nf_conntrack_entries / node_nf_conntrack_entries_limit) > 0.75\n"
        labels:
          severity: error

      - alert: InstanceClockSkewDetected
        annotations:
          description: "Clock skew detected. Clock is out of sync. Ensure NTP is configured correctly on this host.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
          summary: Host clock skew
        expr: ((node_timex_offset_seconds > 0.05 and deriv(node_timex_offset_seconds[5m]) >= 0) or (node_timex_offset_seconds < -0.05 and deriv(node_timex_offset_seconds[5m]) <= 0))
        for: 10m
        labels:
          severity: error

      - alert: InstanceClockNotSynchronising
        annotations:
          description: "Clock on {{ $labels.instance }} is not synchronising. Ensure NTP is configured on this host."
          summary: Host clock not synchronising
        expr: (min_over_time(node_timex_sync_status[1m]) == 0 and node_timex_maxerror_seconds >= 16)
        for: 20m
        labels:
          severity: error

      - alert: HostOutOfInodes
        expr: (node_filesystem_files_free / node_filesystem_files < .10 and ON (instance, device, mountpoint) node_filesystem_readonly == 0)
        for: 2m
        labels:
          severity: error
        annotations:
          summary: Host out of inodes
          description: "Disk is almost running out of available inodes (< 10% left)\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: HostInodesMayFillIn24Hours
        expr: predict_linear(node_filesystem_files_free{fstype!~"^(fuse.*|tmpfs|cifs|nfs)"}[1h], 86400) <= 0 and node_filesystem_files_free > 0
        for: 2m
        labels:
          severity: warn
        annotations:
          summary: Host inodes may fill in 24 hours
          description: "Filesystem will likely run out of inodes within the next 24 hours at current write rate\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: HostFilesystemDeviceError
        expr: node_filesystem_device_error{fstype!~"^(fuse.*|tmpfs|cifs|nfs)",mountpoint!="/boot/efi"} == 1
        for: 2m
        labels:
          severity: error
        annotations:
          summary: Host filesystem device error
          description: "Error stat-ing the {{ $labels.mountpoint }} filesystem\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: HostUnusualDiskReadLatency
        expr: (rate(node_disk_read_time_seconds_total[1m]) / rate(node_disk_reads_completed_total[1m]) > 0.1 and rate(node_disk_reads_completed_total[1m]) > 0)
        for: 2m
        labels:
          severity: warn
        annotations:
          summary: Host unusual disk read latency
          description: "Disk latency is growing (read operations > 100ms)\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: HostUnusualDiskWriteLatency
        expr: (rate(node_disk_write_time_seconds_total[1m]) / rate(node_disk_writes_completed_total[1m]) > 0.1 and rate(node_disk_writes_completed_total[1m]) > 0)
        for: 2m
        labels:
          severity: warn
        annotations:
          summary: Host unusual disk write latency
          description: "Disk latency is growing (write operations > 100ms)\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: HostCpuHighIowait
        expr: avg by (instance) (rate(node_cpu_seconds_total{mode="iowait"}[5m])) > .10
        for: 0m
        labels:
          severity: error
        annotations:
          summary: Host CPU high iowait
          description: "CPU iowait > 10%. Your CPU is idling waiting for storage to respond.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: HostUnusualDiskIo
        expr: rate(node_disk_io_time_seconds_total[5m]) > 0.8
        for: 5m
        labels:
          severity: error
        annotations:
          summary: Host unusual disk IO
          description: "Disk usage >80%. Check storage for issues or increase IOPS capabilities. Check storage for issues.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: HostSystemdServiceCrashed
        expr: (node_systemd_unit_state{state="failed"} == 1)
        for: 0m
        labels:
          severity: error
        annotations:
          summary: Host systemd service crashed
          description: "systemd service crashed\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: HostKernelVersionDeviations
        expr: changes(node_uname_info[1h]) > 0
        for: 0m
        labels:
          severity: warn
        annotations:
          summary: Host kernel version deviations
          description: "Kernel version for {{ $labels.instance }} has changed.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: HostOomKillDetected
        expr: (increase(node_vmstat_oom_kill[1m]) > 0)
        for: 0m
        labels:
          severity: error
        annotations:
          summary: Host OOM kill detected
          description: "OOM kill detected\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
